services:
  - type: web
    name: lgport-creator-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_ORIGIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_SHEET_ID
        value: 1hFkdzit1hxJnbh2DXT4lUn-uCKBpXw2yeAcYF6DOqzQ
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
